dagger/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url('^h/', include('handouts.urls')),
    url('^', include('knowledge.urls')),
]

handouts/urls.py
from django.conf.urls import *

import handouts.views

# place app url patterns here
urlpatterns = patterns('handouts.views',
    url(r'detail/(?P<pk>\d+)/tex', handouts.views.TexHandoutDetail.as_view(),
        name='handout_detail_tex'),
    url(r'detail/(?P<pk>\d+)/', handouts.views.HandoutDetail.as_view(),
        name='handout_detail'),
    url(r'dag/(?P<pk>\d+)/json/$', handouts.views.HandoutDAGjson.as_view(),
        name='handout_json'),
    url(r'dag/(?P<pk>\d+)/', handouts.views.HandoutDAG.as_view(), name='handout_dag'),
    url(r'', handouts.views.HandoutList.as_view(),
        name='handout_list'),
    )

handouts/models.py
from django.db import models
from django.utils.text import slugify
from mptt.models import MPTTModel, TreeForeignKey
from knowledge.models import Atom, AtomType, AtomRelationship
# from random import choice

# Create your models here.

class Paragraph(MPTTModel):
    name = models.CharField(max_length=300)
    slug = models.SlugField(max_length=100)
    parent = TreeForeignKey('self', null=True, blank=True,
                related_name='children', db_index=True)
    order = models.PositiveSmallIntegerField(default=1)
    content = models.ManyToManyField(Atom, through='ParagraphContainsAtoms')
    handout = models.ForeignKey('Handout')

    def ordered_content(self):
        return self.content.all().order_by('paragraphcontainsatoms__order')

    class MPTTMeta:
        level_attr = 'mptt_level'
        order_insertion_by=['order']

    class Meta:
        ordering = ['name',]

class ParagraphContainsAtoms(models.Model):
    paragraph = models.ForeignKey(Paragraph)
    lead_in = models.TextField(blank=True)
    atom = models.ForeignKey(Atom)
    lead_out = models.TextField(blank=True)
    order = models.PositiveSmallIntegerField(default=1)

    class Meta:
        ordering = ['order',]

class Handout(models.Model):
    lead = models.ForeignKey(Paragraph, blank=True, null=True, related_name='handout_as_lead')
    cluster = models.BooleanField(default=False)
    code = models.TextField(help_text='''
Handout code format :<br/>
<br/>
Lead paragraph<br/>
* Main paragraph<br/>
** Sub paragraph<br/>
<br/>
In each paragraph, you can reference atoms:<br/>
Direct reference<br/>
- atom_by_ref<br/>
Reference by relationships<br/>
-> verb atom_by_ref [(all,random,first)]<br/>
Create a new atom and reference it<br/>
-{ typ_slug [slug [name]]<br/>
Atom text goes here<br/>
}<br/>
<br/>
After each atom references you can add text: <br/>
text placed just before the atom to introduce it and can be multiline<br/>
-- (optional separation and signal that )<br/>
the following lines are to be placed after the atom<br/>
''')

    class Meta:
        ordering = ['lead',]

    def atoms(self):
        atoms = []

        for paragraph in self.lead.get_descendants(include_self=True):
            for atom in paragraph.content.filter(typ__important=True):
                if atom not in atoms:
                    atoms.append(atom)

        return atoms

    def __str__(self):
        return self.lead.name

    def save(self, *save_args, **kwargs):
        super(Handout, self).save(*save_args, **kwargs)
        old_lead = self.lead

        lines = self.code.replace('\r','').split('\n') 
        branch = []
        suborder = 1

        lead = Paragraph.objects.create(name=lines[0],
                slug=slugify(lines[0]), handout=self)
        lead.save()
        branch = [ (lead, 1) ]

        processed_lines = [lines[0]]

        def get_tag(i):
            if i >= len(lines):
                return None
            line = lines[i]
            if line == '' or line.strip() == '':
                return None
            return line.strip().split()[0]

        i = 1
        while i < len(lines):
            line = lines[i]
            tag = get_tag(i)
            i += 1
            if line == '':
                processed_lines.append(line)
                continue
            if tag.startswith('-'):
                if tag == '-':
                    processed_lines.append(line)
                    ref = line.split()[1]
                    atom = Atom.objects.by_ref(ref)
                elif tag == '->':
                    processed_lines.append(line)
                    args = line.split()
                    verb = args[1]
                    ref = args[2]

                    # TODO
                    # mult = 'first'
                    # if len(args) > 3:
                    #    mult = args[3]

                    atom = Atom.objects.by_ref(ref)
                    ar = AtomRelationship.objects.get(to_atom=atom,
                            typ__slug=verb)
                    atom = ar.from_atom
                elif tag == '-{':
                    args = line.split()
                    typ_slug = args[1]
                    slug = None
                    name = None
                    if len(args) > 2:
                        slug = args[2]
                        if len(args) > 3:
                            name = ' '.join(args[3:])
                    typ = AtomType.objects.get(slug=typ_slug)
                    atom = Atom.objects.create(typ=typ)
                    if slug:
                        atom.slug = slug
                    atom_text = []
                    while i < len(lines):
                        line = lines[i]
                        i += 1
                        if line != '' and line[0] == '}':
                            break
                        atom_text.append( line )
                    atom.text = '\n'.join(atom_text)
                    atom.slug = slug
                    if name:
                        atom.name = name
                    atom.save()
                    if slug:
                        processed_lines.append('- ' + slug)
                    else:
                        processed_lines.append('- ' + str(atom.id))

                paragraph, _ = branch[-1]
                lead_in = []
                lead_out = []
                leading_out = False
                while i < len(lines):
                    t = get_tag(i)
                    if not t:
                        processed_lines.append(lines[i])
                        i += 1
                        continue
                    if t == '--':
                        leading_out = True
                        processed_lines.append(lines[i])
                        i += 1
                        continue
                    if t[0] in ['-', '*']:
                        break
                    processed_lines.append(lines[i])
                    if leading_out:
                        lead_out.append( lines[i].strip() )
                    else:
                        lead_in.append( lines[i].strip() )
                    i += 1
                lead_in = '\r\n'.join(lead_in)
                lead_out = '\r\n'.join(lead_out)
                pca = ParagraphContainsAtoms.objects.create(paragraph=paragraph,
                        atom=atom, order=suborder,
                        lead_in=lead_in, lead_out=lead_out)
                pca.save()
                suborder += 1
            elif set(tag) == {'*'}:
                processed_lines.append(line)
                suborder = 1
                level = 1 + len(tag)
                name = line.strip()[len(tag):].strip()
                slug = slugify(name)
                if level <= len(branch):
                    while len(branch) > level:
                        branch.pop()
                    _, old_order = branch.pop()
                    order = old_order + 1
                else:
                    order = 1
                parent, _ = branch[-1]
                par = Paragraph.objects.create(name=name, slug=slug,
                        parent=parent, order=order, handout=self)
                par.save()
                branch.append( (par, order) )
        self.lead = lead
        self.code = '\n'.join(processed_lines)
        super(Handout, self).save(*save_args, **kwargs)
        if old_lead:
            old_lead.delete()

handouts/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, TemplateView, UpdateView, CreateView, FormView, RedirectView, DeleteView, View
from django.http import HttpResponseForbidden, HttpResponseRedirect, HttpResponse, Http404

from handouts.models import *
from knowledge.models import *

import json

class HandoutDetail(DetailView):
    model = Handout
    context_object_name = 'handout' 

class TexHandoutDetail(DetailView):
    model = Handout
    context_object_name = 'handout' 
    template_name = 'handouts/handout_detail.tex'
    content_type = 'application/tex'


class HandoutList(ListView):
    model = Handout
    context_object_name = 'handouts' 

class HandoutDAGjson(View):
    model = Handout
    context_object_name = 'handout' 

    def get_atoms(self, handout):
        atoms = []

        for paragraph in handout.lead.get_descendants(include_self=True):
            for atom in paragraph.content.filter(typ__important=True):
                if atom not in atoms:
                    atoms.append(atom)

        return atoms

    def get(self, request, *args, **kwargs):
        handout = get_object_or_404(Handout, pk=kwargs['pk'])
        atoms = self.get_atoms(handout)

        graph = { 'nodes' : [], 'links' : [] }
        for atom in atoms:
            a = { 'id' : atom.id, 'group' : atom.typ.bootstrap_label }
            if atom.slug:
                a['name'] = atom.slug
            else:
                a['name'] = str(atom.id)
            a['full_name'] = str(atom)
            a['url'] = atom.get_absolute_url()
            graph['nodes'].append(a)

        for atom in atoms:
            a = { 'name' : atom.name, 'group' : atom.typ.id }
            for rel in atom.from_atoms.all():
                if rel.to_atom in atoms:
                    link = { 'source' : atom.id,
                            'target' : rel.to_atom.id,
                            'value' : rel.typ.slug }
                    graph['links'].append(link)
            for to_atom, rel_typ in atom.fuse_from_atoms():
                if to_atom in atoms:
                    link = { 'source' : atom.id,
                            'target' : to_atom.id,
                            'value' : rel_typ.slug }
                    graph['links'].append(link)

        return HttpResponse(json.dumps(graph),
                content_type='application/json')


class HandoutDAG(DetailView):
    model = Handout
    context_object_name = 'handout' 
    template_name = 'knowledge/atom_dag.html'

    def get_context_data(self, *args, **kwargs):
        context = super(HandoutDAG, self).get_context_data(*args, **kwargs)
        handout = self.get_object()
        
        context['json'] = '/h/dag/' + str(handout.id) + '/json/'

        return context

handouts/templates/handouts/handout_detail.html
{% extends 'site_base.html' %}
{% load atom %}
{% load handout %}
{% load mptt_tags %}

{% block local_script %}
<script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/qtip2/2.2.1/jquery.qtip.min.js"></script>
<script type="text/javascript" src="/static/knowledge/atom_preview.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js" charset="utf-8"></script>
<script src="/static/knowledge/dagre-d3.min.js" charset="utf-8"></script>
<script type="text/javascript">
$(document).ready(function(){
    var color = d3.scale.category20();

    /*
    var force = d3.layout.force()
        .charge(-220)
        .linkDistance(5)
        .size([width, height]);
    */

    var svg = d3.select('svg')
        .attr('width', $('svg').parent().width())
        .attr('height', 300);
    var svgGroup = svg.append("g");
      var g = new dagreD3.graphlib.Graph()
        .setGraph({
            rankdir: "RL",
            marginx: 20,
            ranksep: 100,
            nodesep: 30
        })
        .setDefaultEdgeLabel(function() { return {}; });

    var zoom = d3.behavior.zoom().on("zoom", function() {
        svgGroup.attr("transform", "translate(" + d3.event.translate + ")" +
                "scale(" + d3.event.scale + ")");
        svgGroup.selectAll('g.node')
            .each(function(v) {
                $(this).qtip('reposition');
            });
    });
    svg.call(zoom);

    var render = new dagreD3.render();

    d3.json("{% url "handout_json" pk=handout.pk %}", function(error, graph) {
      if (error) throw error;

      $.each(graph.nodes, function(i,n) {
          g.setNode(n.id, { label: n.name, full_label : n.full_name,
              class : 'node-' + n.group,
              url : n.url });
      });
      $.each(graph.links, function(i,l) {
          var value = { };
          if (l.value != 'necessite') {
              value.arrowhead = "vee";
              value.label = l.value;
          } else {
              value.style = "fill:none; stroke-dasharray: 5, 5; stroke:#555; stroke-width:0.5px;";
              value.arrowhead = "undirected";
          }
          value.lineInterpolate = 'basis';
          g.setEdge(l.source, l.target, value);
      });

      g.nodes()
        .forEach(function(v) {
            var node = g.node(v);
            node.rx = node.ry = 5;
        });
      render(d3.select("svg g"), g);
      
     var graph_height = g.graph().height + 20;
     var graph_width = g.graph().width;
     var svg_width = svg.attr('width');

      var ratio = g.graph().width / graph_height;
      var ideal_height = svg.attr('width') / ratio;
      svg.attr('height', ideal_height);

      var scale = svg.attr('height') / graph_height;
      var scale_x = svg.attr('width') / g.graph().width;
      if (scale_x < scale)
          scale = scale_x;

      var centerX = -(graph_width*scale - svg_width) / 2;
      var centerY = -(graph_height*scale - ideal_height) / 2 + 20;

      zoom.translate([centerX, centerY]).scale(scale);
      zoom.event(svgGroup.transition().duration(100));

    svgGroup.selectAll('g.node')
        .each(function(v) {
            var node = g.node(v);

            $(this).dblclick(function(e) {
                window.location.href = node.url;
            })
                .qtip({
        content: {
            title: function(event, api) { 
                return node.full_label;
            },
            text: function(event, api) {
                $.ajax({
                    url: node.url
                })
                .then(function(content) {
                    // Set the tooltip content upon successful retrieval
                    var content = $('<div id="mathtooltip"><p>'
                        + $(content).find('#atom_text').html()
                        + '</p></div>');
                    $('body').append(content);
                    content.hide();
                    MathJax.Hub.Queue(
                            ["Typeset", MathJax.Hub, "mathtooltip"],
                            function () {
                                api.elements.content.html(content.html());
                                api.reposition(null, false);
                                content.remove();
                            });
                }, function(xhr, status, error) {
                    // Upon failure... set the tooltip content to the status and error value
                    api.set('content.text', status + ': ' + error);
                });

                return 'Chargement...'; // Set some initial text
            }
        },
        show: 'click', hide : 'click',
        events: {
        },
          position : {
              my: 'left center',
              at: 'right center',
              target: this,
          },
          style : {
              tip : {
                  corner: true
              }
          },
    });
    });


    });

});
</script>

{% endblock %}

{% block extra_style %}
<link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/qtip2/2.2.1/jquery.qtip.min.css"></link>
<style>
g.node-primary > rect {
    fill: #337ab7;
}
g.node-default > rect {
    fill: #858585;
}
g.node-success > rect {
    fill: #5cb85c;
}
g.node-info > rect {
    fill: #5bc0de;
}
g.node-warning > rect {
    fill: #f0ad4e;
}
g.node-danger > rect {
    fill: #d9534f;
}

/*
text {
  font-weight: "bold";
  font-family: "Helvetica Neue", Helvetica, Arial, sans-serf;
  font-size: 12px;
}
*/

.node text {
  fill: white;
}

.node > rect {
  stroke: #555;
  fill: #fff;
  stroke-width: 2px;
}

.edgePath path {
  stroke: #000;
  stroke-width: 1px;
}
</style>
<style>
.panel-definition {
    background-color: #eff !important;
}
.panel-theoreme {
    background-color: #ffe !important;
    font-weight: bold;
}
.panel-preuve {
    background-color: #fee !important;
}
ul .structure {
    margin-left: 0;
    padding-left: 0;
}
</style>
{% endblock %}

{% block extra_nav %}
    <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
        aria-haspopup="true" aria-expanded="false"><b>{{ handout.lead.name|slice:":50" }}...</b><span class="caret"></span></a>
        <ul class="dropdown-menu">
{% for node,structure in handout.lead.get_descendants|tree_info %}
        {% if structure.new_level %}<ul><li>{% else %}</li><li>{% endif %}
            <a href="#node_{{ node.id }}">{{ node|paragraph_number }} - {{ node.name }}</a>
        {% for level in structure.closed_levels %}</li></ul>{% endfor %}
{% endfor %}
        </ul>
    </li>
    <li><a href="{% url 'admin:handouts_handout_change' handout.id %}?source=main">Editer</a></li>
{% endblock %}

{% block body %}
<h2>{{ handout.lead.name }}</h2>
<div class="alert alert-info">
    <strong>Graphe de dépendance des notions</strong><br/>
Cliquez sur un élément pour afficher un apercu, cliquez à nouveau pour le faire disparaitre.<br/>
Navigation: Glisser-déposer depuis le fond du diagramme et zoom avec la molette.
</div>
<div class="well">
    <svg></svg>
</div>
{% for node,structure in handout.lead.get_descendants|tree_info %}
    {% if structure.new_level %}<ul class="structure"><li>{% else %}</li><li>{% endif %}
        <h3 id="node_{{ node.id }}"><strong>{{ node|paragraph_number }} - {{ node.name }}</strong></h3>
    {% for par in node.paragraphcontainsatoms_set.all %}
        {% if par.lead_in %}
        <p>
        {{ par.lead_in|atom_format }}
        </p>
        {% endif %}
        <div class="panel panel-{{ par.atom.typ.bootstrap_label }}">
            <div class="panel-heading">
                <h4 class="panel-title">
                    {{ par.atom.typ }}
                    <a href="{{ par.atom.get_absolute_url }}">
                    <span class="glyphicon glyphicon-info-sign"></span>
                    {% if par.atom.name %}{{ par.atom.name }}{% endif %}
                    </a>
                </h4>
            </div>
            <div class="panel-body">
            {{ par.atom.text|atom_format }}
            </div>
        </div>
        {% if par.lead_out %}
        <p>
        {{ par.lead_out|atom_format }}
        </p>
        <hr/>
        {% endif %}
    {% endfor %}
    {% for level in structure.closed_levels %}</li></ul>{% endfor %}
{% endfor %}
{% endblock %}

handouts/templates/handouts/handout_list.html
{% extends 'site_base.html' %}

{% block body %}
<div class="list-group">
    {% for handout in handouts %}
    <a class="list-group-item" href="{% url 'handout_detail' handout.id %}">{{ handout }}</a>
    {% endfor %}
</div>
{% endblock %}